### ISSUE TITLE
perfsonar upgrade from 3.5.0.x to 3.5.1.x breaks packages and configurations

### ISSUE THREAD

**Issue by rwf14f** [HEP-Puppet/perfsonar#4]
The latest minor perfsonar upgrade changed all the package names, as well as the dependencies between the packages.

**Comment by fmelaccio** [comment]
Hi, I have worked a little bit on this issue, I wilk try to make a pull request with my changes very soon.

**Comment by fmelaccio** [comment]
The pull request is now made and a perfsonar fresh install works.

**Comment by rwf14f** [comment]
Thanks a lot for the PR. I've tested the upgrade from 3.5.0 to 3.5.1 on my test box. The changes are not compatible with a 3.5.0 installation, so a simple auto upgrade is not possible (not without the risk of puppet throwing errors while trying to install non-existent packages or restarting non-existent services). Doing a manual upgrade works nicely:
- disable puppet
- update puppet module
- update perfsonar packages
- restart puppet
I'll also try a fresh install later, but I see no reason why it shouldn't work.

**Comment by rwf14f** [comment]
There are still some wrong paths buried in parts of the module. I've fixed them in my fork and will create a PR when I've finished testing the changes.

**Comment by rwf14f** [comment]
I've successfully updated our production servers as well now and didn't encounter any further problems.
